export const strings = {
  auth: {
    loginTitle:        'Connexion',
    loginSubtitle:     'Bienvenue. Votre parcours vous attend.',
    signupTitle:       'Bienvenue.',
    signupSubtitle:    'Quelques informations pour personnaliser votre parcours. Elles restent strictement privées.',
    labelFirstName:    'Votre prénom',
    labelEmail:        'Adresse e-mail',
    labelPassword:     'Mot de passe',
    placeholderEmail:  'vous@exemple.fr',
    placeholderPw:     '8 caractères minimum',
    hintPassword:      'Vous ne le saisirez qu\'une seule fois — il sera mémorisé.',
    btnCreateAccount:  'Créer mon compte',
    btnLogin:          'Se connecter',
    btnAlreadyAccount: 'J\'ai déjà un compte',
    btnBack:           'Retour',
    errorInvalidEmail: 'Cette adresse e-mail ne semble pas valide.',
    errorWeakPassword: 'Le mot de passe doit contenir au moins 8 caractères.',
    errorGeneric:      'Une erreur est survenue. Veuillez réessayer.',
    legalNotice:       'En continuant, vous acceptez nos conditions d\'utilisation et notre politique de confidentialité.',
  },
  home: {
    greeting:        (prenom: string) => `Bonjour, ${prenom}.`,
    tagline:         'Avancez à votre rythme.',
    sectionParcours: 'Votre parcours',
    sectionToday:    'Aujourd\'hui',
    sectionThought:  'Une pensée pour ce soir',
    weekLabel:       (n: number) => `Semaine ${n}`,
    daysLabel:       (done: number, total: number) => `${done} jour${done > 1 ? 's' : ''} sur ${total}`,
    daysDoneLabel:   (done: number) => `${done} jour${done > 1 ? 's' : ''}`,
    checkinWeight:   'Pesée du matin',
    checkinJournal:  'Journal du jour',
    signOut:         'Se déconnecter',
    thoughts: [
      'Qu\'est-ce qui vous a donné de l\'énergie aujourd\'hui, même en petite quantité ?',
      'Quel petit geste avez-vous fait pour vous aujourd\'hui ?',
      'Qu\'avez-vous appris sur vous-même cette semaine ?',
      'Quelle chose simple vous a apporté du plaisir aujourd\'hui ?',
      'De quoi êtes-vous fière, en ce moment ?',
      'Qu\'aimeriez-vous vous dire ce soir avec bienveillance ?',
      'Quel moment de cette journée souhaitez-vous garder en mémoire ?',
    ],
  },
  tabs: {
    home:     'Accueil',
    journey:  'Parcours',
    journal:  'Journal',
    aliments: 'Aliments',
    suivi:    'Progrès',
    settings: 'Réglages',
  },
  onboarding: {
    step1Title:        'Quelques mots sur vous.',
    step1Subtitle:     'Ces informations nous permettent de calculer votre parcours personnalisé. Elles restent strictement privées.',
    labelAge:          'Votre âge',
    placeholderAge:    'Ex. 52',
    ageTooYoung:       'Cette méthode a été pensée pour les femmes de 45 ans et plus. Vous pouvez continuer, mais sachez que certains conseils sont adaptés à cette tranche d\'âge.',
    ageAlertTitle:     'Un moment d\'attention',
    ageAlertConfirm:   'Je continue quand même',
    disclaimerTitle:   'Avis médical important',
    disclaimerText:    'Cette application propose un accompagnement basé sur l\'indice glycémique. Elle ne remplace pas un suivi médical. En cas de doute sur votre état de santé, consultez votre médecin avant de commencer.',
    disclaimerAccept:  'J\'ai lu et je comprends',
    step2Title:        'Votre point de départ.',
    step2Subtitle:     'Ces mesures servent uniquement à calculer votre parcours et suivre vos progrès.',
    labelWeight:       'Poids actuel (kg)',
    labelTargetWeight: 'Poids souhaité (kg)',
    labelHeight:       'Taille (cm)',
    labelWaist:        'Tour de taille (cm)',
    labelHips:         'Tour de hanches (cm)',
    placeholderWeight: 'Ex. 72',
    placeholderHeight: 'Ex. 165',
    placeholderMeasure:'Ex. 88',
    optionalHint:      'Facultatif',
    step3Title:        'Votre parcours.',
    step3Subtitle:     'Voici ce que nous avons calculé pour vous.',
    labelStartDate:    'Date de démarrage',
    phaseOffensive:    'Phase offensive',
    phaseDestockage:   'Phase de déstockage',
    phaseStabilisation:'Stabilisation',
    weeks:             (n: number) => `${n} semaine${n > 1 ? 's' : ''}`,
    indefinite:        'À vie',
    summaryIntro:      'À votre rythme, sans vous presser.',
    btnNext:           'Continuer',
    btnStart:          'Démarrer mon parcours',
    errorRequired:     'Veuillez remplir tous les champs obligatoires.',
    errorInvalidNumber:'Veuillez entrer un nombre valide.',
  },
  weight: {
    title:           'Suivi du poids',
    labelToday:      'Poids aujourd\'hui (kg)',
    placeholder:     'Ex. 68,5',
    btnSave:         'Enregistrer',
    btnEdit:         'Modifier',
    saving:          'Enregistrement…',
    savedMessage:    'Pesée enregistrée.',
    noData:          'Aucune pesée enregistrée pour le moment.',
    chartTitle:      '30 derniers jours',
    initialLabel:    'Départ',
    currentLabel:    'Actuel',
    goalLabel:       'Objectif',
    kgUnit:          'kg',
    errorInvalid:    'Veuillez entrer un poids valide.',
  },
  foods: {
    title:          'Aliments',
    searchPlaceholder: 'Rechercher un aliment…',
    listVerte:      'Liste verte',
    listOrange:     'Liste orange',
    listRouge:      'Liste rouge',
    listVerteDesc:  'À privilégier — indice glycémique bas',
    listOrangeDesc: 'Avec modération — indice glycémique moyen',
    listRougeDesc:  'À éviter — indice glycémique élevé',
    igLabel:        'IG',
    emptySearch:    'Aucun aliment ne correspond à votre recherche.',
    premiumBadge:   'Premium',
    premiumMessage: 'Les listes orange et rouge sont disponibles dans la version Premium.',
  },
  journal: {
    headerLabel:     (date: string) => `Journal du ${date}`,
    headerTitle:     'Comment allez-vous ?',
    moods: [
      { key: 'difficile', emoji: '😔', label: 'Difficile' },
      { key: 'neutre',    emoji: '😐', label: 'Neutre'   },
      { key: 'bien',      emoji: '🙂', label: 'Bien'     },
      { key: 'legere',    emoji: '😊', label: 'Légère'   },
    ],
    q1Label:         'Quelle a été votre plus belle réussite aujourd\'hui ?',
    q1Placeholder:   'Grande ou petite, elle compte…',
    q2Label:         'Qu\'est-ce qui vous a donné de l\'énergie ?',
    q2Placeholder:   'Une conversation, un moment de calme…',
    q3Label:         'Qu\'est-ce qui vous en a pris ?',
    q3Placeholder:   'Sans jugement, juste observer…',
    q4Label:         'Votre intention pour demain ?',
    q4Placeholder:   'Une seule chose, concrète…',
    btnSave:         'Enregistrer mon journal',
    btnEdit:         'Modifier',
    savedMessage:    'Journal enregistré.',
    alreadySaved:    'Votre journal du jour est déjà enregistré.',
    saving:          'Enregistrement…',
  },
  errors: {
    networkError: 'Impossible de se connecter. Vérifiez votre connexion.',
    sessionExpired: 'Votre session a expiré. Veuillez vous reconnecter.',
  },
} as const;
