export const strings = {
  auth: {
    loginTitle:        'Connexion',
    loginSubtitle:     'Bienvenue. Votre parcours vous attend.',
    signupTitle:       'Bienvenue.',
    signupSubtitle:    'Quelques informations pour personnaliser votre parcours. Elles restent strictement privées.',
    labelFirstName:    'Votre prénom',
    labelEmail:        'Adresse e-mail',
    labelPassword:     'Mot de passe',
    placeholderEmail:  'vous@exemple.fr',
    placeholderPw:     '8 caractères minimum',
    hintPassword:      'Vous ne le saisirez qu\'une seule fois — il sera mémorisé.',
    btnCreateAccount:  'Créer mon compte',
    btnLogin:          'Se connecter',
    btnAlreadyAccount: 'J\'ai déjà un compte',
    btnBack:           'Retour',
    errorInvalidEmail: 'Cette adresse e-mail ne semble pas valide.',
    errorWeakPassword: 'Le mot de passe doit contenir au moins 8 caractères.',
    errorGeneric:      'Une erreur est survenue. Veuillez réessayer.',
    legalNotice:       'En continuant, vous acceptez nos conditions d\'utilisation et notre politique de confidentialité.',
  },
  home: {
    greeting:  (prenom: string) => `Bonjour, ${prenom}.`,
    tagline:   'Votre parcours commence ici.\nAvancez à votre rythme.',
    sectionParcours: 'Votre parcours',
    sectionToday:    'Aujourd\'hui',
    sectionThought:  'Une pensée pour ce soir',
  },
  tabs: {
    home:    'Accueil',
    journey: 'Parcours',
    journal: 'Journal',
    progress:'Progrès',
    settings:'Réglages',
  },
  errors: {
    networkError: 'Impossible de se connecter. Vérifiez votre connexion.',
    sessionExpired: 'Votre session a expiré. Veuillez vous reconnecter.',
  },
} as const;
