export const strings = {
  auth: {
    loginTitle:        'Connexion',
    loginSubtitle:     'Bienvenue. Votre parcours vous attend.',
    signupTitle:       'Bienvenue.',
    signupSubtitle:    'Quelques informations pour personnaliser votre parcours. Elles restent strictement privées.',
    labelFirstName:    'Votre prénom',
    labelEmail:        'Adresse e-mail',
    labelPassword:     'Mot de passe',
    placeholderEmail:  'vous@exemple.fr',
    placeholderPw:     '8 caractères minimum',
    hintPassword:      'Vous ne le saisirez qu\'une seule fois — il sera mémorisé.',
    btnCreateAccount:  'Créer mon compte',
    btnLogin:          'Se connecter',
    btnAlreadyAccount: 'J\'ai déjà un compte',
    btnBack:           'Retour',
    errorInvalidEmail: 'Cette adresse e-mail ne semble pas valide.',
    errorWeakPassword: 'Le mot de passe doit contenir au moins 8 caractères.',
    errorGeneric:      'Une erreur est survenue. Veuillez réessayer.',
    legalNotice:       'En continuant, vous acceptez nos conditions d\'utilisation et notre politique de confidentialité.',
  },
  home: {
    greeting:  (prenom: string) => `Bonjour, ${prenom}.`,
    tagline:   'Votre parcours commence ici.\nAvancez à votre rythme.',
    sectionParcours: 'Votre parcours',
    sectionToday:    'Aujourd\'hui',
    sectionThought:  'Une pensée pour ce soir',
  },
  tabs: {
    home:    'Accueil',
    journey: 'Parcours',
    journal: 'Journal',
    progress:'Progrès',
    settings:'Réglages',
  },
  onboarding: {
    step1Title:        'Quelques mots sur vous.',
    step1Subtitle:     'Ces informations nous permettent de calculer votre parcours personnalisé. Elles restent strictement privées.',
    labelAge:          'Votre âge',
    placeholderAge:    'Ex. 52',
    ageTooYoung:       'Cette méthode a été pensée pour les femmes de 45 ans et plus. Vous pouvez continuer, mais sachez que certains conseils sont adaptés à cette tranche d\'âge.',
    ageAlertTitle:     'Un moment d\'attention',
    ageAlertConfirm:   'Je continue quand même',
    disclaimerTitle:   'Avis médical important',
    disclaimerText:    'Cette application propose un accompagnement basé sur l\'indice glycémique. Elle ne remplace pas un suivi médical. En cas de doute sur votre état de santé, consultez votre médecin avant de commencer.',
    disclaimerAccept:  'J\'ai lu et je comprends',
    step2Title:        'Votre point de départ.',
    step2Subtitle:     'Ces mesures servent uniquement à calculer votre parcours et suivre vos progrès.',
    labelWeight:       'Poids actuel (kg)',
    labelTargetWeight: 'Poids souhaité (kg)',
    labelHeight:       'Taille (cm)',
    labelWaist:        'Tour de taille (cm)',
    labelHips:         'Tour de hanches (cm)',
    placeholderWeight: 'Ex. 72',
    placeholderHeight: 'Ex. 165',
    placeholderMeasure:'Ex. 88',
    optionalHint:      'Facultatif',
    step3Title:        'Votre parcours.',
    step3Subtitle:     'Voici ce que nous avons calculé pour vous.',
    labelStartDate:    'Date de démarrage',
    phaseOffensive:    'Phase offensive',
    phaseDestockage:   'Phase de déstockage',
    phaseStabilisation:'Stabilisation',
    weeks:             (n: number) => `${n} semaine${n > 1 ? 's' : ''}`,
    indefinite:        'À vie',
    summaryIntro:      'À votre rythme, sans vous presser.',
    btnNext:           'Continuer',
    btnStart:          'Démarrer mon parcours',
    errorRequired:     'Veuillez remplir tous les champs obligatoires.',
    errorInvalidNumber:'Veuillez entrer un nombre valide.',
  },
  errors: {
    networkError: 'Impossible de se connecter. Vérifiez votre connexion.',
    sessionExpired: 'Votre session a expiré. Veuillez vous reconnecter.',
  },
} as const;
