export const theme = {
  colors: {
    background:  '#F4F6FA',
    backgroundHeader: '#E4E9F5',
    backgroundSplash: '#CDD5EC',
    primary:     '#4A6B9A',
    primaryDark: '#3A5A88',
    accent:      '#8AAAD4',
    card:        '#FFFFFF',
    border:      '#C8D5E8',
    badge:       '#E4E9F5',
    inputBg:     '#F8FAFD',
    textDark:    '#121E30',
    textMid:     '#1E3050',
    textSoft:    '#4A6B9A',
    textMuted:   '#90A8C4',
    journalBg:   '#D4E0EC',
    journalAccent: '#5A8AAA',
    journalText: '#4A7090',
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 16,
    lg: 24,
    xl: 32,
    xxl: 48,
  },
  fontSize: {
    xs:   11,
    sm:   13,
    md:   15,
    lg:   17,
    xl:   24,
    xxl:  32,
  },
  fontFamily: {
    serif: 'Georgia',
  },
  borderRadius: {
    sm:  8,
    md:  12,
    lg:  18,
    full: 999,
  },
  touchTarget: 44,
} as const;
